challenge 04 finish
Miguelcutri/CURSO-JS-NINJA-EXERCICIOS pull request #3
Opened 2024-01-26 00:19 UTC by Miguelcutri

challenge 04 finish

2024-01-31 16:49 UTC, priscilaandreani requested changes

2024-01-31 16:49 UTC, priscilaandreani commented on challenge-04.js
> +const isTruthy = function (a) {
resposta alternativa:

`const isTruthy = (param) => param? true : false `

2024-01-31 16:49 UTC, priscilaandreani commented on challenge-04.js
> +    return "true";
true e false são valores booleanos, não precisam ser passados como string ;)

2024-01-31 16:49 UTC, priscilaandreani commented on challenge-04.js
> +function getModel() {
opss, aqui repetiu o nome da função

2024-01-31 16:49 UTC, priscilaandreani commented on challenge-04.js
> +    var peoplesNumbers = `O carro já está lotado!`;
será que precisamos mesmo redeclarar a variavel todas as vezes?

2024-01-31 16:49 UTC, priscilaandreani commented on challenge-04.js
> +console.log(addPeoplesInCar());
aqui deveria acessar o objeto para verificar quantas pessoas tem no carro!

2024-02-02 00:17 UTC, Miguelcutri commented on challenge-04.js
> +    return "true";
foi mera desatenção kkk

2024-02-07 23:17 UTC, priscilaandreani commented on challenge-04.js
> +  } else if (newNumberOfPeoples < 0) {
Hmmm aqui acho que temos outra função, que seria de remover pessoas?  Não entendi muito bem.

2024-02-07 23:20 UTC, priscilaandreani commented on challenge-04.js
> +    return "true";
👁️

2024-02-19 23:21 UTC, merged